### ISSUE TITLE
List all available models

### ISSUE THREAD

**Issue by klieret** [SWE-agent/SWE-agent#224]
Ideally, this should be e.g., in the `--help` text and be fetched based on `models.py`, so that it can't go out of date.

**Comment by hminsky2002** [comment]
@klieret Hello! I don't have much experience with machine learning itself but I feel like this issue would be in my wheelhouse, could I fork and make a PR? Would love to contribute to the project!

**Comment by hminsky2002** [comment]
@klieret I ended up making a pr, happy to edit/refactor as needed!

**Comment by klieret** [comment]
All models are now handled by litellm.
