### ISSUE TITLE
Implement llama.cpp and grammars

### ISSUE THREAD

**Issue by talentoscope** [SWE-agent/SWE-agent#246]
### Describe the feature

I would like to propose the integration of llama.cpp into the SWE-agent project. llama.cpp is another solution besides ollama but which allows the use of grammar files, which may be crucial for improving the accuracy and consistency of local LLM outputs with this project.
By having an implementation for grammar files, we can significantly enhance the capability of local LLMs to adhere to the required output format, which could potentially bring locally-hosted LLMs up to par with commercial models.

### Potential Solutions

[llama.cpp grammars](https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md)

**Comment by ofirpress** [comment]
Local LMs are so weak right now, I don't really think a forced output format would help much. In addition, our output format is not complex enough I don't think to warrant this? If anyone tries this and it would we would be open to integrating.

**Comment by ofirpress** [comment]
We're going to add support for something like LiteLLM therefore this issue will be deprecated. Closing.
