### ISSUE TITLE
os.set_blocking not available on Windows

### ISSUE THREAD

**Issue by SyedMuqtasidAli** [SWE-agent/SWE-agent#618]
Experts kindly guide about
### Describe the issue

I want to run SWE agent web ui on locally on windows so for this i clone the repo in my drive and then i create an conda environment with python=3.10 and then i install all dependencies and librarie.
Then i run flask server through this command : 
cd sweagent/api/
python server.py and server is running fine here is screenshoot:
![image](https://github.com/princeton-nlp/SWE-agent/assets/107794270/bc59ae9f-f5fe-4ea6-8373-530bfe561780)

Then i open new conda prompt and again activate the environment and run these commands 👍 
cd sweagent/frontend
npm start
and application will start running on localhost:3000 but when i gives a issue url i am getting this issues : 
![image](https://github.com/princeton-nlp/SWE-agent/assets/107794270/0ed0dafe-603a-45de-97a7-6198a79a3812)

**Comment by panozzaj** [comment]
@SyedMuqtasidAli please do not @ message random people for your issues. Kindly see https://github.com/princeton-nlp/SWE-agent/issues/609#issuecomment-2191766755 for another instance of this.

**Comment by SyedMuqtasidAli** [comment]
@panozzaj did you get what is this issue for ? why i am getting this ?

**Comment by SyedMuqtasidAli** [comment]
@klieret kindly i am not getting any good resources about for intsalling Web ui of SWE-agent kindly guide me about this.

**Comment by klieret** [comment]
This should finally be solved with the new way of executing of code using https://swe-rex.com
