### ISSUE TITLE
Support parallel testing with pytest-xdist 

### ISSUE THREAD

**Issue by klieret** [SWE-agent/SWE-agent#670]
Currently some tests will break because of the multithreading.

Reproduce:

```bash
pip install pytest-xdist
pytest -n auto
```

**Comment by 7259324177** [comment]
Mira que me siento solo y el tiempo aquí se detiene

**Comment by klieret** [comment]
Thanks for your interest @aksh16. This has now been fixed with swe-agent 1.0.
