### ISSUE TITLE
Does it support private deployment of k8s?

### ISSUE THREAD

**Issue by renguoliang** [SWE-agent/SWE-agent#862]
### Describe the issue

First of all, thank you for the open source project so that we can learn from it. Based on the previous version, we built a private k8s cluster to achieve local development and remote scheduling. I would like to ask whether the new version can support the private k8s cluster?

**Comment by klieret** [comment]
Hi @renguoliang, great to hear that! I'm not sure if I understand your setup correctly. It sounds like you execute code on your k8s cluster to run the agent in parallel/on different environments?

That will definitely work even easier with the new version! With [swe-rex](https://swe-rex.com/), we communicate with a deployment (the place where we execute the sandboxed code) by interacting with its web API. So as long as you run the swe-rex runtime/server in your container, swe-agent will be able to talk it. 

Very concretely:

1. Start the swe-rex server in your container
2. As deployment for swe-agent, choose the `RemoteDeployment` from swe-rex and provide your IP/port to it

**Comment by renguoliang** [comment]
ok. thanks
